variables:
  PROJECT_TYPE: "npm"

# creator_ci:
#   trigger:
#     include: 
#     - local: packages/native-modules-prebuilds-creator/.gitlab-ci.yml
#     strategy: depend

patcher_ci:
  trigger:
    include: 
    - local: packages/native-modules-prebuilds-patcher/.gitlab-ci.yml
    strategy: depend

release:
  script: 
  - echo "released"
  - echo ${CI_PROJECT_PATH}
  - echo ${CI_COMMIT_BRANCH}
  when: manual
  artifacts:
    paths: 
    - packages/native-modules-prebuilds-patcher/package.json
    expire_in: 30 mins