variables:
  PROJECT_TYPE: "npm"

stages:
# - patcher_ci
- release


# creator_ci:
#   trigger:
#     include: 
#     - local: packages/native-modules-prebuilds-creator/.gitlab-ci.yml
#     strategy: depend

# patcher_ci:
#   stage: patcher_ci
#   trigger:
#     include: 
#     - local: packages/native-modules-prebuilds-patcher/.gitlab-ci.yml
#     strategy: depend

release:
  stage: release
  scripts:
  - [.base_prepare, script]
  - [.base_npm_release-prepare, script]
  when: manual
  artifacts:
    paths: 
    - packages/native-modules-prebuilds-patcher/package.json
    expire_in: 30 mins