include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml

stages:
- prepare
- before-release-scripts
- release
- after-release-scripts


prepare:
  stage: prepare
  extends: .base_npm_prepare

creator-before-release-scripts:
  stage: before-release-scripts
  trigger:
    include: 
    - local: packages/native-modules-prebuilds-creator/.gitlab-ci/before-release.yml
    strategy: depend

patcher-before-release-scripts:
  stage: before-release-scripts
  trigger:
    include: 
    - local: packages/native-modules-prebuilds-patcher/.gitlab-ci/before-release.yml
    strategy: depend

release:
  stage: release
  script:
  - !reference [.base_npm_release-prepare, script]
  - !reference [.base_release-upload, script]
  needs: 
  - job: prepare
    artifacts: true
  - job: creator-before-release-scripts
  - job: patcher-before-release-scripts
  when: manual

creator-after-release-scripts:
  stage: after-release-scripts
  trigger:
    include: 
    - local: packages/native-modules-prebuilds-creator/.gitlab-ci/after-release.yml
    strategy: depend
  needs: 
  - job: release

pacther-after-release-scripts:
  stage: after-release-scripts
  trigger:
    include: 
    - local: packages/native-modules-prebuilds-patcher/.gitlab-ci/after-release.yml
    strategy: depend
  needs: 
  - job: release