include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml

stages:
# - patcher_ci
- prepare
- release


# creator_ci:
#   trigger:
#     include: 
#     - local: packages/native-modules-prebuilds-creator/.gitlab-ci.yml
#     strategy: depend

# patcher_ci:
#   stage: patcher_ci
#   trigger:
#     include: 
#     - local: packages/native-modules-prebuilds-patcher/.gitlab-ci.yml
#     strategy: depend


prepare:
  stage: prepare
  extends: .base_npm_prepare

release:
  stage: release
  script:
  - !reference [.base_npm_release-prepare, script]
  - !reference [.base_release-upload, script]
  needs: 
  - job: prepare
    artifacts: true
  when: manual