variables:
  SUBPATH: packages/native-modules-prebuilds-patcher

before_script:
- cd ${SUBPATH}

include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml

stages:
- prepare
- build
- deploy-to-self-host
- deploy-to-npm

patcher_prepare:
  stage: prepare
  extends: .monorepo_prepare
  artifacts:
    paths: 
    - node_modules/
    - ${SUBPATH}/node_modules/
    - ${SUBPATH}/.npmrc
    - ${SUBPATH}/.accesstoken
    expire_in: 30 mins
    reports:
      dotenv: ${SUBPATH}/build.env

patcher_build:
  stage: build
  extends: .base_npm_build
  needs: 
  - job: patcher_prepare
    artifacts: true
  script:
    - yarn
    - yarn run build
  artifacts:
    paths: 
    - ${SUBPATH}/dist/

patcher_deploy-to-self-host:
  stage: deploy-to-self-host
  extends: .base_npm_package
  needs: 
  - job: patcher_build
    artifacts: true
  - job: patcher_prepare
    artifacts: true
  variables:
    DEPLOY_TO_SELF_HOST: "true"
    DEPLOY_TO_NPM: "false"
    PATH_TO_USE: ./dist
  when: manual

patcher_deploy-to-npm:
  stage: deploy-to-npm
  extends: .base_npm_package
  needs: 
  - job: patcher_build
    artifacts: true
  - job: patcher_prepare
    artifacts: true
  variables:
    DEPLOY_TO_SELF_HOST: "false"
    DEPLOY_TO_NPM: "true"
    PATH_TO_USE: ./dist
  when: manual