before_script:
- cd packages/native-modules-prebuilds-patcher

include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml

stages:
- prepare
- test
- build

prepare:
  stage: prepare
  extends: .monorepo_prepare
  artifacts:
    paths: 
    - node_modules/
    - packages/native-modules-prebuilds-patcher/node_modules/
    - packages/native-modules-prebuilds-patcher/.npmrc
    - packages/native-modules-prebuilds-patcher/.accesstoken
    expire_in: 30 mins
    reports:
      dotenv: packages/native-modules-prebuilds-patcher/build.env

test:
  stage: test
  script: 
  - yarn
  - yarn run test
  needs: 
  - job: prepare
    artifacts: true

build:
  stage: build
  extends: .base_npm_build
  needs: 
  - job: test
  - job: prepare
    artifacts: true
  script:
    - yarn
    - yarn run build

