variables:
  SUBPATH: packages/native-modules-prebuilds-creator

before_script:
- cd ${SUBPATH}

include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml

stages:
- prepare
- test
- build

creator_prepare:
  stage: prepare
  extends: .monorepo_prepare
  artifacts:
    paths: 
    - node_modules/
    - ${SUBPATH}/node_modules/
    - ${SUBPATH}/.npmrc
    - ${SUBPATH}/.accesstoken
    expire_in: 30 mins
    reports:
      dotenv: ${SUBPATH}/build.env

creator_test:
  stage: test
  script: 
  - yarn
  - yarn run test
  needs: 
  - job: creator_prepare
    artifacts: true

creator_build:
  stage: build
  extends: .base_npm_build
  needs: 
  - job: creator_test
  - job: creator_prepare
    artifacts: true
  script:
    - yarn
    - yarn run build

