before_script:
- cd native-modules-prebuilds-creator


include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml


stages:
- prepare
- test
- build
- release
- deploy-to-self-host
- deploy-to-npm

prepare:
  stage: prepare
  extends: .base_npm_prepare
  artifacts:
    paths: 
    - node_modules/
    - native-modules-prebuilds-creator/.npmrc
    - native-modules-prebuilds-creator/.accesstoken
    - native-modules-prebuilds-creator/${CN_PROJECT_FILE}
    - native-modules-prebuilds-creator/${PROJECT_TYPE_CONFIG_FILE}
    expire_in: 30 mins
    reports:
      dotenv: native-modules-prebuilds-creator/build.env

test:
  stage: test
  script: 
  - ls -l
  - cat package.json
  - > 
    echo -e "@centrid:registry=https://gitlab.com/api/v4/projects/$CENTRID_PACKAGE_REPO_PROJ_ID/packages/npm/\n//gitlab.com/api/v4/projects/$CENTRID_PACKAGE_REPO_PROJ_ID/packages/npm/:_authToken=$CENTRID_ACCESS_TOKEN" >> .npmrc
  - >
    echo "{ \"host\": \"https://gitlab.com\", \"token\": \"${CENTRID_ACCESS_TOKEN}\", \"user\": \"${CENTRID_USERNAME}\", \"projectId\": \"${CENTRID_PACKAGE_REPO_PROJ_ID}\", \"packageTypeLimit\": 10 }" > .accesstoken
  - yarn 
  - yarn add @centrid/cendevops
  - ls -la node_modules/.bin
  - cat package.json
  - !reference [.install_cendevops, script]
  # - yarn run test
  - echo test
  needs: 
  - job: prepare
    artifacts: true

build:
  stage: build
  extends: .base_npm_build
  needs: 
  - job: test
  - job: prepare
    artifacts: true
  script:
    - !reference [.base_npm_build, script]
    - yarn run build
  artifacts:
    paths: 
    - dist/

release:
  stage: release
  needs: 
  - job: build
    artifacts: true
  - job: prepare
    artifacts: true
  script:
  - !reference [.base_npm_release-prepare, script]
  - !reference [.base_release-upload, script]
  when: manual

deploy-to-self-host:
  stage: deploy-to-self-host
  extends: .base_npm_package
  needs: 
  - job: build
    artifacts: true
  - job: release
  variables:
    DEPLOY_TO_SELF_HOST: "true"
    DEPLOY_TO_NPM: "false"
    PATH_TO_USE: ./dist
  when: manual


deploy-to-npm:
  stage: deploy-to-npm
  extends: .base_npm_package
  needs: 
  - job: build
    artifacts: true
  - job: release
  variables:
    DEPLOY_TO_SELF_HOST: "false"
    DEPLOY_TO_NPM: "true"
    PATH_TO_USE: ./dist
  when: manual