before_script:
- cd native-modules-prebuilds-creator


include:
- project: centrid/packagerepositry
  ref: master
  file: GitlabCIScripts/centrid-npm-ci.yml


stages:
- prepare
- test
- build
- release
- deploy-to-self-host
- deploy-to-npm

prepare:
  stage: prepare
  extends: .base_npm_prepare

test:
  stage: test
  script: 
  - yarn run test
  needs: 
  - job: prepare
    artifacts: true
  artifacts:
    paths: 
    - node_modules/
    - .npmrc
    - .accesstoken
    - ${PROJECT_TYPE_CONFIG_FILE}

build:
  stage: build
  extends: .base_npm_build
  needs: 
  - job: test
    artifacts: true
  script:
    - !reference [.base_npm_build, script]
    - yarn run build
  artifacts:
    paths: 
    - dist/
    - node_modules/
    - .npmrc
    - .accesstoken
    - ${PROJECT_TYPE_CONFIG_FILE}

# release:
#   stage: release
#   script:
#   - !reference [.base_npm_release-prepare, script]
#   - !reference [.base_release-upload, script]
#   when: manual

deploy-to-self-host:
  stage: deploy-to-self-host
  extends: .base_npm_package
  needs: 
  - job: build
    artifacts: true
  variables:
    DEPLOY_TO_SELF_HOST: "true"
    DEPLOY_TO_NPM: "false"
    PATH_TO_USE: ./dist
  when: manual


deploy-to-npm:
  stage: deploy-to-npm
  extends: .base_npm_package
  needs: 
  - job: build
    artifacts: true
  variables:
    DEPLOY_TO_SELF_HOST: "false"
    DEPLOY_TO_NPM: "true"
    PATH_TO_USE: ./dist
  when: manual